server:
  port: 8081
spring:
  r2dbc:
    url: r2dbc:postgresql://124.70.38.253:6543/chat_gpt
    username: postgres
    password: 1212
  webflux:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
      time: HH:mm:ss
    multipart:
      max-in-memory-size: 10MB
      max-parts: 3
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
  main:
    allow-bean-definition-overriding: true
  codec:
    max-in-memory-size: 10MB
  data:
    redis:
      username: anii
      password: A01610228FE998F515A72DD730294D87
      host: 124.70.38.253
      port: 7480
      repositories:
        enabled: false
      connect-timeout: 5s
      timeout: 5s

logging:
  level:
    org:
      springframework:
        r2dbc: debug

gpt:
  timeout: 10s
  proxy:
    enable: true
  token: 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

minio:
  access-key: lXjqJfLL142i3o4rmvPh
  secret-key: o2Pico4MmJCBkk7Fvju3c11m5Mm6JiUC3OLUyeJV
  endpoint: http://124.70.38.253:9000
  gpt:
    bucket: gpt-images
    image-prefix: images