### 注册
POST http://127.0.0.1:8081/auth/register
Content-Type: application/json

{
  "username": "anii2",
  "password": "1212"
}

### 登录
POST http://127.0.0.1:8081/auth/login
Accept: application/json;charset=utf-8
Content-Type: application/json

{
  "username": "anii2",
  "password": "1212"
}

###
#> {% client.global.set("token", response.body.data) %}

###
