### 注册
POST http://127.0.0.1:8081/auth/register
Content-Type: application/json

{
  "username": "anii",
  "password": "1212"
}

### 登录
POST http://127.0.0.1:8081/auth/login
Accept: application/json;charset=utf-8
Content-Type: application/json

{
  "username": "anii",
  "password": "1212"
}

> {%
    client.global.set("token", response.body.data)
%}


### 新建角色
POST http://127.0.0.1:8081/chat/role/
Accept: application/json;charset=utf-8
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "command": "你是一个好帮手",
  "model": "GPT_35_TURBO",
  "nickName": "好帮手4",
  "welcome": "你好",
  "mark": "nnnnn"
}

### 查询全部角色
GET http://127.0.0.1:8081/chat/role/
Accept: application/json;charset=utf-8
Authorization: Bearer {{token}}

### 查询指定角色
GET http://127.0.0.1:8081/chat/role/1
Accept: application/json;charset=utf-8
Authorization: Bearer {{token}}

### 更新角色
PUT http://127.0.0.1:8081/chat/role/1
Accept: application/json;charset=utf-8
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "command": "你是谁",
  "model": "GPT_35_TURBO",
  "nickName": "好帮手5",
  "welcome": "你好",
  "mark": "nnnnn"
}

### 删除指定角色
DELETE http://127.0.0.1:8081/chat/role/1
Authorization: Bearer {{token}}

### 创建聊天
POST http://127.0.0.1:8081/chat/
Accept: application/json;charse;,t=utf-8
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "roleId": 1
}

### 查询聊天
GET http://127.0.0.1:8081/chat/1
Accept: application/json;charse;,t=utf-8
Authorization: Bearer {{token}}

### 更新聊天
PUT http://127.0.0.1:8081/chat/1
Accept: application/json;charset=utf-8
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "contextNum": 10
}

### 删除聊天
DELETE http://127.0.0.1:8081/chat/1
Accept: application/json;charset=utf-8
Authorization: Bearer {{token}}

### 聊天
POST http://127.0.0.1:8081/chat/1/stream
#Accept: application/json;charset=utf-8
Accept: application/x-ndjson
#Accept: text/event-stream
#Accept: application/stream+json
Authorization: Bearer {{token}}



###
POST https://api.openai.com/v1/chat/completions
Accept: application/json
Content-Type: application/json
Authorization: Bearer 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

{
  "model": "gpt-3.5-turbo-16k",
  "messages": [
    {
      "role": "user",
      "content": "你是谁"
    }
  ]
}

