### 注册
POST http://127.0.0.1:8081/auth/register
Content-Type: application/json

{
  "username": "anii",
  "password": "1212"
}

### 登录
POST http://127.0.0.1:8081/auth/login
Accept: application/json;charset=utf-8
Content-Type: application/json

{
  "username": "anii",
  "password": "1212"
}

> {%
    client.global.set("token", response.body.data)
%}


### 新建角色
POST http://127.0.0.1:8081/chat/role/
Accept: application/json;charset=utf-8
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "command": "你是一个好帮手",
  "model": "GPT_35_TURBO",
  "nickName": "好帮手4",
  "welcome": "你好",
  "mark": "nnnnn"
}

### 查询全部角色
GET http://127.0.0.1:8081/chat/role/
Accept: application/json;charset=utf-8
Authorization: Bearer {{token}}

### 查询指定角色
GET http://127.0.0.1:8081/chat/role/1
Accept: application/json;charset=utf-8
Authorization: Bearer {{token}}

### 更新角色
PUT http://127.0.0.1:8081/chat/role/4
Accept: application/json;charset=utf-8
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "command": "你是谁",
  "model": "GPT_35_TURBO",
  "nickName": "好帮手4",
  "welcome": "你好",
  "mark": "nnnnn"
}

### 删除指定角色
DELETE http://127.0.0.1:8081/chat/role/1
Authorization: Bearer {{token}}
